### ISSUE TITLE
Linking the lib is not working

### ISSUE THREAD

**Issue by engmsaleh** [chirag04/react-native-in-app-utils#106]
I have installed the library using `npm install` and tried to link it using `npm link` but the project didn't link and I have to go and link it manually.

**Comment by ryancoughlin** [comment]
What version of RN and this package are you running? Also what did it fail on? It's helpful to supply more information. 

`react-native link` should work with the latest.

**Comment by mcanobbio** [comment]
I have a Issue like that, I'm using the command `react-native install react-native-in-app-utils` and when I'm trying to use

`const { InAppUtils } = NativeModules`

I get InAppUtils undefined, also in Xcode don't see any of InAppUtils, I think must be a guide to linking manually

**Comment by chirag04** [comment]
@mcanobbio try to manually link react-native-in-app-utils if it's not already linked.

**Comment by mcanobbio** [comment]
thanks @chirag04 i did it and works fine 👍

**Comment by chirag04** [comment]
Glad it worked out
