### ISSUE TITLE
Empty array on in_app receipt field / Implement SKReceiptRefreshRequest

### ISSUE THREAD

**Issue by brunolemos** [chirag04/react-native-in-app-utils#111]
Some users are complaining they are paying and not receiving the subscription.

Debugging the server, I noticed it receives the same receipt-data from the user on every `receiptData` request, with an empty array on `in_app` field.

After searching some links (e.g. [this one](https://stackoverflow.com/a/36010764/2228575)), I believe we need to call Apple's `SKReceiptRefreshRequest` method to get an updated receipt from Apple's server.  

Is that correct to assume? Or maybe another thing is causing this issue?

Apple [docs](https://developer.apple.com/library/content/technotes/tn2413/_index.html#//apple_ref/doc/uid/DTS40016228-CH1-RECEIPT-MY_APP_VALIDATES_ITS_RECEIPT_WITH_THE_APP_STORE_VIA_PAYMENTQUEUE_UPDATEDTRANSACTIONS__AFTER_A_SUCCESSFUL_PURCHASE__HOWEVER__THE_RETURNED_RECEIPT_CONTAINS_AN_EMPTY_IN_APP_ARRAY_RATHER_THAN_THE_EXPECTED_PRODUCTS_): 

> An empty in_app array indicates that StoreKit has not recorded any transactions for that user yet. It may be that the application receipt has not yet been updated. When this happens, your app can inform the user that the receipt does not appear current and ask whether to refresh it. Upon user agreement, your app should use the SKReceiptRefreshRequest class to update the receipt. At this point, if StoreKit has recorded a purchase for the user, your app receipt will show it in in_app. See [Refreshing the App Receipt](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Restoring.html#//apple_ref/doc/uid/TP40008267-CH8-SW2) for more information on how to update a receipt.

**Comment by chirag04** [comment]
there is a PR in works for refreshReceipt. let's continue there: https://github.com/chirag04/react-native-in-app-utils/pull/110

**Comment by lazyhoneyant** [comment]
@brunolemos Do you solve this problem by refresh? I have the same issue too. the receipt has no in_app fields,(empty array []). but refresh didn't solve it.

**Comment by brunolemos** [comment]
@lazyhoneyan no, I haven't looked at this probably anymore, not sure if I still have it, users stopped complaining
