### ISSUE TITLE
SKPaymentTransactionStatePurchased on launch are discarded

### ISSUE THREAD

**Issue by vafada** [chirag04/react-native-in-app-utils#113]
I'm doing Auto-Renew Subscription and in sandbox, Apple auto renew every 5 minutes for 6 times. when i close my app and reopen within that 30 minute window. i get a warning `No callback registered for transaction with state purchased.` (https://github.com/chirag04/react-native-in-app-utils/blob/master/InAppUtils/InAppUtils.m#L59) which make sense because there is no callback tied to that product id since this was invoked in the background.

The app shouldn't be discarding these transactions. Maybe put them in some cache and export a method to retrieve and flush this cache.

**Comment by chirag04** [comment]
i have not done auto renewable subscriptions but this is one more example of why the callback api is not the right way to go.

ideally we should have an event driven api like something like:
```
inapputils.addListener('purchased', function cb(productId) {
 // unlock store etc here.
});
```

This is going to be a major breaking change but i think that's the way forward.

**Comment by superandrew213** [comment]
@chirag04 we can keep the callback api and add event api too.

I think the issue is with calling addTransactionObserver in objective c init. User should call this in js code as early as possible. This is needed for both callback & event api.
