### ISSUE TITLE
TouchID and iTunes password

### ISSUE THREAD

**Issue by tronin** [chirag04/react-native-in-app-utils#118]
Hi, guys, thank you for the plugin. I have a question for you:
I've never seen a touch id window in my app then I've trying to purchase my iap, at this time I've tested my app a few months and every time I have password filed for purchasing. Have you any idea why this is happening? 

And yes, I've using TouchID in other applications

**Comment by chirag04** [comment]
i think this depends on the settings you have for your apple id. There is nothing touchId related to this module afaict. Let me know if we should reopen this.

**Comment by ajonno** [comment]
we are seeing this too, i actually opened a new ticket

**Comment by a-koka** [comment]
I noticed this all the time when using a sandbox account. For real production purchases, it shows the TouchID. Are you testing a sandbox purchase?

**Comment by ajonno** [comment]
yes we're testing at moment via sandbox. are you saying that once it's in production this issue should go away ?

**Comment by a-koka** [comment]
In my experience, this happens only for sandbox accounts. You can easily verify this by testing on a device with a non-sandbox iTunes account. It'll show the TouchID. You do not have to go through the purchase.
