### ISSUE TITLE
how can i use it with Expo ?

### ISSUE THREAD

**Issue by jpca999** [chirag04/react-native-in-app-utils#130]

**Comment by chirag04** [comment]
I don’t think expo is supported. I guess this question is better suited for the expo community forums.

**Comment by jpca999** [comment]
@chirag04  so if I build my app with usual CRNA ( react native cli ) , would i be able to use your package then?

**Comment by chirag04** [comment]
i think so. if not yet ejecting will def work.

**Comment by jpca999** [comment]
@chirag04 I wanna be sure, I don't want to "eject".

**Comment by chirag04** [comment]
@jpca999 only to be sure is to try it :) I don't use CRNA.

**Comment by jpca999** [comment]
What do you use @chirag04
