### ISSUE TITLE
[Question] How purchaseProductForUser really works?

### ISSUE THREAD

**Issue by lucianomlima** [chirag04/react-native-in-app-utils#134]
I've implemented the purchaseProductForUser for a monthly subscription, and I'm passing firebase user UID.
But when I change the user in app (but keep the same iTunes account on device), which has another UID, I can restore the previous user's purchases.

The purchaseProductForUser and restorePurchasesForUser methos works per iTunes account?
Or does passing different UID to the same iTunes account should work properly?

**Comment by lucianomlima** [comment]
Some one?

**Comment by NachtRitter** [comment]
> The purchaseProductForUser and restorePurchasesForUser methos works per iTunes account?

As far as I know, purchases are linked to iTunes account.

**Comment by lucianomlima** [comment]
Then what is the purpose of the purchaseProductForUser if using different username will get products from same account without restriction?

**Comment by superandrew213** [comment]
@lucianomlima I'm seeing the same issue. `restorePurchasesForUser` restores all purchases and not just the user's.

**Comment by superandrew213** [comment]
@RalfNieuwenhuizen is this still working for you? I can see that you added this feature.
