### ISSUE TITLE
undefined is not an object (evaluating 'InAppUtils.loadProducts')

### ISSUE THREAD

**Issue by hugoh1995** [chirag04/react-native-in-app-utils#153]
I'm stuck on this for a few days, I've seen the previous issue when they fixed it by reinstalling the app in the simulator but it didn't work for me. Any idea howI could fix it? I've also followed the guide from react native on making sure libraries are linked...

**Comment by hugoh1995** [comment]
I'm not sure how I managed to make it work but after doing another detach and multiple uninstall / install of the package I managed to make it work in the end. I'm now stuck at getting back the products from the loadProducts method.

**Comment by BenBach** [comment]
@hugoh1995 How did you resolve this?

**Comment by guopeng1994** [comment]
i'm in this trouble too! and i dont know how to resolve it.i need help!!!!

**Comment by tombaki** [comment]
in same problem !!

**Comment by temitope** [comment]
same problem on device and simulator...

**Comment by malithjkmt** [comment]
I also encountered this issue. 
`react-native install react-native-in-app-utils` didn't linked the InAppUtils library.
Had to [link manually](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking) 
Now it works fine!

**Comment by hisshash** [comment]
You may have to cd into `ios` and run `pod install`

**Comment by jitadlak** [comment]
React native InappUtils works on android app ?
i Have same error on android project
