### ISSUE TITLE
Is it possible to use touch id when make the purchase?

### ISSUE THREAD

**Issue by wilbyang** [chirag04/react-native-in-app-utils#159]

**Comment by jirihradil** [comment]
+1

**Comment by Vilitsa** [comment]
+1

**Comment by AhadCove** [comment]
I looked into this and was willing to do it natively, but it doesn't seem like there's a way. Basically, Apple handles what is displayed, and during development, it would just be an alert. In production, I heard Touch ID would show if you have it available. Can anyone confirm this?

**Comment by Vilitsa** [comment]
@AhadCove yes! Now we send our app to production. If iphone have this function, it show Touch ID.

**Comment by chirag04** [comment]
Thanks for confirming. I’m going to close this since there are not changes required.
