### ISSUE TITLE
loadProducts method never triggers callback when there's no network connection

### ISSUE THREAD

**Issue by agolovenko** [chirag04/react-native-in-app-utils#16]
Hi!

Awesome job, I really like your plugin. This is just a minor annoying thing and of course I can check network before invoking loadProducts. But other methods seem to return at least some error in the absence of network.

Thanks,
Ashot

**Comment by wasedaigo** [comment]
Oh yeah, I have the same issue.

**Comment by wasedaigo** [comment]
PR sent

**Comment by BodySplash** [comment]
fix in #99 (and merged).
@chirag04 any idea when it will published to npm ?

**Comment by chirag04** [comment]
published.
