### ISSUE TITLE
'Breaking Change' warning is confusing

### ISSUE THREAD

**Issue by stevehanson** [chirag04/react-native-in-app-utils#162]
The readme says: 

> Breaking Change: Due to a major breaking change in RN 0.40+, Use v5.x of this lib when installing from npm.

There are a couple things about this that are unclear to me:

- Who does this breaking change affect? I.e. should users of RN less than 0.40 use a specific version of this library?
- Is the problem with v4 of this library or the newer v6? Is it safe to use the newer v6?

**Comment by chirag04** [comment]
We need to update the readme. 
```
Breaking Change: Due to a major breaking change in RN 0.40+, Use v5 or higher version of this lib when installing from npm.
```

**Comment by chirag04** [comment]
want to send a PR?

**Comment by stevehanson** [comment]
@chirag04 sounds good and thanks for the clarification. I'll go ahead and submit a PR!
