### ISSUE TITLE
requiresMainQueueSetup warning

### ISSUE THREAD

**Issue by rangav** [chirag04/react-native-in-app-utils#164]
Hi

The RN is warning about requiresMainQueueSetup missing. i think we should return YES

```
+ (BOOL)requiresMainQueueSetup
{
  return YES;
}
```

**Comment by anonrig** [comment]
Any pull request on this?

**Comment by airlaser** [comment]
https://github.com/chirag04/react-native-in-app-utils/pull/175

This is fixed but not in a release. You can point to the commit directly.
