### ISSUE TITLE
LoadProducts() return empty array

### ISSUE THREAD

**Issue by NarekChang** [chirag04/react-native-in-app-utils#189]
I added library in my xcode project and installed npm module and created puchases in iTunes Connect, but LoadProducts return only empty array. What am I doing wrong? Did I miss something? I'm used simulator and real device for build testing.

**Comment by NarekChang** [comment]
That's my fault. You need point purchases id's. I'm pointed my app id 👍 

`InAppUtils.loadProducts(['purchasId1', 'purchasId2'], (err, products) => {`
`      console.log(err);`
`      console.log(products);`
`    });`

**Comment by jose920405** [comment]
Thanks @NarekChang 

I think that is confused in the examples the `identifiers` it looks like the `bundle identifier`. 

Thanks for clarification.

![screen shot 2019-02-15 at 11 15 14 am](https://user-images.githubusercontent.com/12536184/52869240-31bb2a00-3113-11e9-8c15-d83fe903dffb.png)

**Comment by 13ArturBruno** [comment]
I am Confused, What the problem with identifiers ? @

**Comment by NarekChang** [comment]
@13ArturBruno Nothing now

**Comment by 13ArturBruno** [comment]
I have a problem.

I can not return the products I added to my app on apple connect, I use the same productId from there, and even then the return comes empty. can you help me ?:

**Comment by jose920405** [comment]
hi @13ArturBruno, 

are you follow this threads?

https://stackoverflow.com/questions/7947805/ios-in-app-purchase-no-products-received/11707704#11707704

https://developer.apple.com/library/archive/technotes/tn2259/_index.html

**Comment by NarekChang** [comment]
@13ArturBruno Do you can show ur code?

**Comment by 13ArturBruno** [comment]
@jose920405 yes, i follow this steps..

**Comment by 13ArturBruno** [comment]
@NarekChang 

i load product with 

```lang-js
const identifiers = [
   'br.com.myapp.premium',
];

InAppUtils.loadProducts(identifiers, (error, products) => {
   console.log(products);
});
```

**Comment by 13ArturBruno** [comment]
My app was rejected, can I still use the products on it?

**Comment by jose920405** [comment]
@13ArturBruno 

I'm not sure about Apple's handling of rejected applications when talking about subscriptions. But it would not make sense that somehow this functionality is affected.

Let's review the following points:

1) 'br.com.myapp.premium', -> You have clear that this string is the `product ID` from the subscription and not the bundle identifier?

2) Your subscritions status is in `Ready to Submit`?.

3) Are you logged correctly in your real device with the Sandbox Tester Account?

4) Are you enable `in-app purchase` inside `Capabilities` tab?.

5) are you verified the response from `canMakePayments`?
