### ISSUE TITLE
payment modal ui style

### ISSUE THREAD

**Issue by dengue8830** [chirag04/react-native-in-app-utils#207]
I want the AppStore payment modal looks like this one (it's not my app, just one that i found in appstore)

![IMG_0119](https://user-images.githubusercontent.com/5104213/57552912-c06eca00-7343-11e9-888a-e73571398530.PNG)

but with this (and others) lib i get this one

![IMG_0115](https://user-images.githubusercontent.com/5104213/57552924-cbc1f580-7343-11e9-9cfa-a744159b2820.PNG)

I understand that it is the system dialog, but is this a style for sandbox tests? if i release to production it will become the cool modal?

**Comment by superandrew213** [comment]
This is only for Sandbox environment.

**Comment by dengue8830** [comment]
it seems that it's the case, based on [this](https://www.reddit.com/r/reactnative/comments/babgn4/iosreact_native_inapppurchases_specific_popup/ekdw39w/) and other opinions
