### ISSUE TITLE
InAppUtils.purchaseProduct() doesn't work on iOS 14

### ISSUE THREAD

**Issue by tecshogo** [chirag04/react-native-in-app-utils#224]
Hello,
I am using the version 6.0.2 on iOS 14 and I find InAppUtils.purchaseProduct() doesn't work.
After purchase completion messages, the loader doesn't disappear.

On iOS 13 the loader disappears and purchase succeeds.

I think this link is related to this issue.
https://github.com/dooboolab/react-native-iap/pull/1064

Please fix this issue.

**Comment by freespaceWeb** [comment]
I have same issue

**Comment by brianomchugh** [comment]
Same issue. The purchase does go through, but the app does not detect it or see the receipt. The only way to get it is to force quit the app and then "Restore Purchase"

**Comment by tecshogo** [comment]
@chirag04 
Could you please check this issue?

**Comment by nasmuris** [comment]
I've made [some changes](https://github.com/lingokids/react-native-in-app-utils/pull/7), so far it seems to be working for me

**Comment by chirag04** [comment]
@nasmuris that looks perfect. mind opening a PR here?
