### ISSUE TITLE
Fix crash on simulator with this small change

### ISSUE THREAD

**Issue by benadamstyles** [chirag04/react-native-in-app-utils#230]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

After upgrading to Xcode 12.5 and iOS 14 simulators, I am no longer able to test in-app purchases on the Xcode simulators using the real network – you now need to [create a StoreKit configuration file](https://developer.apple.com/documentation/storekit/in-app_purchase/testing_in-app_purchases_in_xcode?language=objc) which then allows the simulator to perform in-app purchases locally, however, in this scenario, `appStoreReceiptURL` (called [here](https://github.com/chirag04/react-native-in-app-utils/blob/master/InAppUtils/InAppUtils.m#L206)) is `nil`, which causes a complete app **crash** on [this line](https://github.com/chirag04/react-native-in-app-utils/blob/master/InAppUtils/InAppUtils.m#L260) because `dictionaryWithDictionary` cannot accept `nil` values.

My proposed fix is to return `null` in that case, which `dictionaryWithDictionary` _does_ accept and which therefore avoids a crash on the simulator.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-in-app-utils/InAppUtils/InAppUtils.m b/node_modules/react-native-in-app-utils/InAppUtils/InAppUtils.m
index cf860da..f35fff3 100644
--- a/node_modules/react-native-in-app-utils/InAppUtils/InAppUtils.m
+++ b/node_modules/react-native-in-app-utils/InAppUtils/InAppUtils.m
@@ -253,11 +253,12 @@ - (void)request:(SKRequest *)request didFailWithError:(NSError *)error{
 }
 
 - (NSDictionary *)getPurchaseData:(SKPaymentTransaction *)transaction {
+    NSString *receipt = [self grandUnifiedReceipt];
     NSMutableDictionary *purchase = [NSMutableDictionary dictionaryWithDictionary: @{
         @"transactionDate": @(transaction.transactionDate.timeIntervalSince1970 * 1000),
         @"transactionIdentifier": transaction.transactionIdentifier,
         @"productIdentifier": transaction.payment.productIdentifier,
-        @"transactionReceipt": [self grandUnifiedReceipt]
+        @"transactionReceipt": receipt ? receipt : [NSNull null]
     }];
     // originalTransaction is available for restore purchase and purchase of cancelled/expired subscriptions
     SKPaymentTransaction *originalTransaction = transaction.originalTransaction;
```

If you are happy with this change I can make a PR.

**Comment by chirag04** [comment]
@benadamstyles sure. that sounds like a simple fix. Feel free to open a PR.
