### ISSUE TITLE
Join packages

### ISSUE THREAD

**Issue by sibelius** [chirag04/react-native-in-app-utils#26]
Are this package related to this one - https://github.com/satya164/react-native-in-app-purchase ?

can u join them?

it looks like it has android support 

@satya164 what do u think about it? ur package support monthly subscriptions ?(https://github.com/chirag04/react-native-in-app-utils/issues/25)

**Comment by satya164** [comment]
I'm not actively working on it anymore. Open to hand it over to anyone who wants to continue working on it.

**Comment by chirag04** [comment]
@sibelius initial goal was to merge the two packages. Happy to accept a PR here or on satya's package that merges the two codebases.
