### ISSUE TITLE
Exception raised when restoring purchases 

### ISSUE THREAD

**Issue by adambutler** [chirag04/react-native-in-app-utils#36]
After making a purchase (as a sandbox user) when I try to restore my purchases it results in an exception being raised in `InAppUtils.m` -

```
2016-07-25 14:40:14.240 [info][tid:NSOperationQueue 0x17003a1e0 :: NSOperation 0x17424bdf0 (QOS: LEGACY)][RCTPerformanceLogger.m:41] Unbalanced calls start/end for tag 0
2016-07-25 14:40:16.617 CookAndCount[6892:2261038] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(0x1856342d8 0x1973080e4 0x1855209c8 0x1855207f8 0x100213294 0x185514cdc 0x18a00ceb0 0x18a00c40c 0x18a00d6cc 0x1003d0fd4 0x1003d0f94 0x1003d5c28 0x1855eb7f8 0x1855e98a0 0x1855152d4 0x18ef6b6fc 0x18a112f40 0x1000e7e68 0x1979b2a08)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

![image](https://cloud.githubusercontent.com/assets/1238468/17103494/73a12d8a-5276-11e6-8daf-c8c2a08b9c14.png)

The state is shown here -

![image](https://cloud.githubusercontent.com/assets/1238468/17103513/857338a0-5276-11e6-825c-0295165f3ec0.png)

**Comment by chirag04** [comment]
can you see if any of those `transaction` values are nil?

**Comment by adambutler** [comment]
@chirag04 Yes `transaction.originalTransaction` is nil.

`transaction.transactionIdentifier` & `transaction.payment.productIdentifier` seem ok.

FYI the type of purchase was a recurring subscription. Seems to be a similar report [here](http://stackoverflow.com/questions/8501518/ios-skpaymenttransactionstaterestored-originaltransaction-nil) but I'm no Obj-C dev.

**Comment by chirag04** [comment]
Ah.  `subscriptions` are def not supported or atleast i never tested it. Seems like a minor fix for supporting `subscriptions`. Can you PR?

**Comment by adambutler** [comment]
I'd love to but I really wouldn't be much help as I've never written Obj-C before. Anyone else able to help out here?

**Comment by tokenvolt** [comment]
@adambutler @chirag04 I had the same issue, but only for subscriptions that were deleted in iTunes Connect. So the steps to reproduce this bug:

1. Create a subscription (in my case it was auto-renewable).
2. Create a sandbox user.
3. Make a purchase in application.
4. Delete a subscription.
5. Restore purchases.
6. Experience a bug.

Creating a new sandbox user without any subscriptions works fine. Seems like this should be handled by the library, but unfortunately my Obj-C knowledge is below zero, so I can't help with any coding.

**Comment by codler** [comment]
I have the same issue
