### ISSUE TITLE
I keep getting invalid_product error

### ISSUE THREAD

**Issue by ssmlee04** [chirag04/react-native-in-app-utils#37]
I created a item in iTunes Connect and the In-App Purchase Summary is as follows: 

Reference Name: Glass
Product ID: com.singleglass.glass
Type: Non-Consumable
Apple ID: 1135803760

And then I tried to load products using

```
var products = [
   'com.singleglass.glass',
];
InAppUtils.loadProducts(products, (error, products) => {
   // invalid_product error here...
});
```

It does not work. I keep getting invalid_product errors here. 

Is there something that I did wrong? 

p.s: In-App Purchase Details is in `Waiting for Screenshot` status. But it seems that I cannot get the IAP to work before I can submit a screen shot right?

**Comment by chirag04** [comment]
Make sure your product is cleared for sale and it usually takes some time to test your product. usually 24hrs.

duplicate: https://github.com/chirag04/react-native-in-app-utils/issues/29

Let's continue to discuss on #29

**Comment by ssmlee04** [comment]
ya somehow it is working now. Thanks!
