### ISSUE TITLE
`purchaseProduct` returns `invalid_product` unless you call `loadProducts` first.

### ISSUE THREAD

**Issue by joshuapinter** [chirag04/react-native-in-app-utils#39]
You need to call `loadProducts` first and then call `purchaseProduct` either at a later time or in the callback for `loadProducts`.

At the very least the README should reflect this. 

But, ideally, `purchaseProduct` should work without having to call `loadProducts` first.

Let me know your thoughts on this to make sure we're on the same page before I do a PR.

**Comment by chirag04** [comment]
that's just how apple designed their sdk. I don't know if we can do anything here.

**Comment by joshuapinter** [comment]
@chirag04 Not really, though, right? Can't we just remove that cache you've created involving the `products` variable and just call the purchase method with the specified product identifier?

Why do we need to load the products as a requirement for purchasing a product?

**Comment by chirag04** [comment]
unless i'm mistaken there is no api for purchasing a product directly with a product identifier. you need to make a request to load it first.

loading product first can be useful in cases where you want to show the product price in local currency first.

**Comment by joshuapinter** [comment]
Okay, I gotcha! Thanks again for all your help and creating this library. I'm well on my way now. :)

**Comment by joshuapinter** [comment]
Just as a final thought, you could trigger a load of the products when somebody calls the `purchaseProduct` and just use the product identifier that they supplied.

**Comment by chirag04** [comment]
i would rather prefer that to be in the userland. if users want to load products automatically, they just write a wrapper function on top of purchase product that does it for them.

**Comment by joshuapinter** [comment]
Fair enough man. Well, with the additional README hints, this should help clear things up for others. 👍

**Comment by dwilt** [comment]
To @joshuapinter 's point, here's what we're doing:

```js
export async function purchase(identifier) {
    await loadProducts(identifier);
    return purchaseProduct(identifier);
}
```

**Comment by chirag04** [comment]
Be careful to check for loadProduct failures.

**Comment by wilbyang** [comment]
I have created a product with type being 'Non-consumable' and status 'Waiting for review'. In my project code, I am trying to load the product, with the right indentifier, but the repsonse contains no products and just something like _invalidindentifers staff (get it from debugging windows). Does I mis-understanding some staff. I have been in this trap/trouble for one week.

**Comment by wilbyang** [comment]
I have created a product with type being 'Non-consumable' and status 'Waiting for review'.  I am trying to load the product, with the right indentifier, but the repsonse contains no products and just something like _invalidindentifers staff (get it from debugging windows). Does I mis-understanding some staff. I have been in this trap/trouble for one week.
