### ISSUE TITLE
add transactionReceipt to callback

### ISSUE THREAD

**Issue by marcgreenstock** [chirag04/react-native-in-app-utils#4]
Great work on this library! And thank you for building it.

Would it be possible to put the `transactionReceipt` in the `purchaseProduct` callback?

It's a property on the `transaction` object.

See [iOS Developer docs](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/DeliverProduct.html#//apple_ref/doc/uid/TP40008267-CH5-SW18)

**Comment by chirag04** [comment]
Sure. Happy to accept a PR for this.

We can change the current api to have an object in the callback like below.


```
var productIdentifier = 'com.xyz.abc';
InAppUtils.purchaseProduct(productIdentifier, (error, response) => {
  var identifier = response.identifier;
  var transactionReceipt = response. transactionReceipt; 
  if(identifier) {
      //unlock store here.
   }
});
```

**Comment by marcgreenstock** [comment]
Hi @chirag04, cool, I'm taking a stab at it now, my knowledge of Object-C is limited.

Apparently `transactionReceipt` is deprecated as on iOS 7. That is what xcode tells me anyway.

The right way is to use `appStoreReceiptURL`.

This is what I have in mind so far.

```Objective-C
case SKPaymentTransactionStatePurchased: {
  NSString *key = RCTKeyForInstance(transaction.payment.productIdentifier);
  NSURL *receiptUrl = [[NSBundle mainBundle] appStoreReceiptURL];
  NSData *receiptData = [NSData dataWithContentsOfURL:receiptUrl];
  // TODO: Convert receiptData into an NSString
  // TODO: Create an NSDictionary for the success argument in the callback
}
```

Not sure how to convert `receiptData` into an `NSString` though, this [Stackoverflow question](http://stackoverflow.com/questions/18924411/how-to-get-ios-appstorereceipturl-into-base-64-encoded-string) points in the right direction but I'm having trouble implementing the `base64forData` method.

**Comment by chirag04** [comment]
Cool. I will take a look over weekend.

**Comment by marcgreenstock** [comment]
@chirag04 just created https://github.com/chirag04/react-native-in-app-utils/pull/5 for this.

**Comment by chirag04** [comment]
Sorry for the delay. Little busy with the release. Will review and merge as soon as i get some time. Thanks.

**Comment by marcgreenstock** [comment]
@chirag04 no dramas, let me know if you have any questions.

**Comment by chirag04** [comment]
2.0.0 is published on npm.

**Comment by Cordazar** [comment]
> "TransactionRecepit" is deprecated. First deprecated in IOS 7.0 - Use - [NSBundle appstoreReceiptURL]

I still get this warning during buildtime on version 5.4.0

**Comment by marcgreenstock** [comment]
Unless there is a way to suppress deprecation warnings, you will get this warning on build. The fact that [transactionReceipt](https://github.com/chirag04/react-native-in-app-utils/blob/master/InAppUtils/InAppUtils.m#L54) is referenced in the code is enough to raise the warning.

It won't cause your app any problems, as the warning states it was deprecated in favour of `appstoreReceiptURL` since 7.0, it's in 11 now and the method still exists and the receipts are still valid for use with the apple's receipt validation API.
