### ISSUE TITLE
undefined is not an object NativeModules.InAppUtils.loadProducts

### ISSUE THREAD

**Issue by emretekince** [chirag04/react-native-in-app-utils#49]
Why? I did link the package using rnpm
<img width="365" alt="screen shot 2016-10-07 at 14 11 22" src="https://cloud.githubusercontent.com/assets/5754074/19188069/fe863660-8c97-11e6-921a-6e2d05f83924.png">

**Comment by chirag04** [comment]
can you double check if rnpm automatically did step 1 and 2 mentioned here: https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking

**Comment by emretekince** [comment]
Yes I have checked..

**Comment by emretekince** [comment]
Ok I solved by removing app from simulator and installing again by xcode in debug env.

**Comment by ncpope** [comment]
Reinstalling on the simulator fixed this issue for me as well.

**Comment by novakben** [comment]
@ncpope @emretekince  Just a note: Do not test in-app purchase on a simulator, only on real devices.

**Comment by hugoh1995** [comment]
Can you give more guidance and how do you "reinstall again by xcode in debug env" ? @emretekince @ncpope

**Comment by marco-souza** [comment]
Hi guys, same error here in iPhone 5s, **not on emulator**.
Everything is linked and installed, I've updated `node_modules`, removed the app and installed it again, cleaned everything from `ios/build`, cleaned the project using Xcode and I still receiving this same error.

I'm stuck more than 2 weeks trying to make the in-app purchase work on a real device. 

@chirag04 (or anyone) Could you give us some help?

**Comment by NachtRitter** [comment]
@marco-souza Try to delete folders in location ~/Library/Developer/Xcode/DerivedData.
Sometimes it helps with different troubles of packages.

**Comment by temitope** [comment]
@marco-souza same issue here any luck?

**Comment by malithjkmt** [comment]
`react-native install react-native-in-app-utils` didn't linked the InAppUtils library.
Had to [link manually](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking) 
Now it works fine!

**Comment by diegomelo182** [comment]
Hi guys, i'm solved dropping "node_modules/react-native-in-app-utils/InAppUtils.xcodeproj" file to Libraries using XCode and add libInAppUtils.a in "Link Binary With Libraries" on "Build Phases" and now it works!

**Comment by bakystefan** [comment]
$(SRCROOT)/../react-native/React
add in header search 
replace #import <React/RCTBridgeModule.h> with #import "RCTBridgeModule.h"
before replace it, do this:
Make sure you have `rnpm` installed: `npm install rnpm -g`
Install with rnpm: `rnpm install react-native-in-app-utils`

:D
