### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by macuna** [chirag04/react-native-in-app-utils#51]
Hi,

After I run rnpm install react-native-in-app-utils I got this error.

<img width="370" alt="screen shot 2016-11-12 at 1 50 37 pm" src="https://cloud.githubusercontent.com/assets/63238/20239467/7860b79a-a8df-11e6-900f-163c8fbb871f.png">

Log file:

<Error>: Native module cannot be null.
<Critical>: Unhandled JS Exception: Native module cannot be null.
<Error>: Requiring module "191", which threw an exception.
<Critical>: Unhandled JS Exception: Requiring module "191", which threw an exception.
<Error>: Module AppRegistry is not a registered callable module.
<Critical>: Unhandled JS Exception: Module AppRegistry is not a registered callable module.

Any advice ?

**Comment by Froelund** [comment]
Which version of react-native are you on?

**Comment by macuna** [comment]
React Native: 0.32
Xcode: 8.1

**Comment by chirag04** [comment]
i haven't tried rnpm integration. See if it works when linking it manually.

**Comment by macuna** [comment]
Where a can see how to do the  the manually integration ?

Thanks

**Comment by ignu** [comment]
I had this problem but it went away after running `Clean` in XCode.

**Comment by anilkumar1505** [comment]
I am facing this issue in react native version 0.57.0
