### ISSUE TITLE
Crashlytics reporting StoreKit exception: SKProductsRequest handleReply

### ISSUE THREAD

**Issue by iury** [chirag04/react-native-in-app-utils#53]
Hello,

We are starting to receive the following crash report:
http://crashes.to/s/400617489c8

Any thoughts about what could be causing the issue?

**Comment by chirag04** [comment]
are you able to replicate this locally? might be when putting the app in background?

Also:
http://stackoverflow.com/questions/24675528/ios-crash-report-skproductsrequest

**Comment by iury** [comment]
unfortunately I'm not able to replicate. so far this affected only 2 users of 147 using the version released few hours ago. previous versions of the app weren't affected by this crash, so I'm not sure if we screwed something up or is just a random error. I'll be monitoring and will keep in touch

**Comment by iury** [comment]
dig into the source code, the productsRequest in https://github.com/chirag04/react-native-in-app-utils/blob/master/InAppUtils/InAppUtils.m#L147 should be a strong reference, no? Apple docs at https://developer.apple.com/reference/storekit/skproductsrequest remarks "be sure to keep a strong reference to the request object; otherwise, the system might deallocate the request before it can complete."

**Comment by chirag04** [comment]
yeah. good find. Can you send a PR?

**Comment by iury** [comment]
https://github.com/chirag04/react-native-in-app-utils/pull/48 seems to be exact about it
