### ISSUE TITLE
Apple rejected my app because it isn't IPv6 compatible

### ISSUE THREAD

**Issue by macuna** [chirag04/react-native-in-app-utils#54]
Hi, after I implemented this library apple rejected my latest app. 

This is the rejection message:
> We discovered one or more bugs in your app when reviewed on iPad and iPhone running iOS 10.1.1 on Wi-Fi connected to an IPv6 network.
> 
> Specifically, we received an error message when we tapped on the “Purchase No Ads version” button.
> 
> We've attached screenshot(s) for your reference.
> 
> Next Steps
> 
> Please run your app on a device while connected to an IPv6 network (all apps must support IPv6) to identify the issue(s), then revise and resubmit your app for review.
> 
> If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.

I fact I tested in a IPv6 network but everything is working fine.

Any advice about what could be wrong?

Thanks a lot

**Comment by chirag04** [comment]
I'm not sure what's going on. I have apps that uses this module and approved by apple. Without much info, i'm not sure if i can help. I suggest trying to replicate this on your device.

let me know if we need to reopen this.

**Comment by alexkuttig** [comment]
We experience a similar issue here. The InApp purchase is working fine in our beta build but when the review team is reviewing the exact same build, the InApp purchase does not get loaded. Any ideas?
We are submitting a TSI in the meantime...

**Comment by chirag04** [comment]
Only way to be sure is to reproduce. I would suggest running a release build on your device and see the logs.

As far as i know `IPv6`/networking has nothing to do with this lib.

**Comment by chirag04** [comment]
also: http://stackoverflow.com/questions/37637818/ipv6-app-store-rejection

**Comment by alexkuttig** [comment]
Thanks for the fast response. I think I posted the Issue within the wrong Github Issue. Just to clarify - at first we also got rejected because of IPv6/networking. Then we explained that we tested on IPv6 only network and we got rejected because of "However we noticed that while you have submitted in-app purchase products for your app, the in-app purchase functionality is not present in your binary.". Attached was a screenshot of our purchase page, but without the purchase button (which means that the purchase does not get loaded).

**Comment by alexkuttig** [comment]
Hey, 
just to keep you updated about this issue. I submitted a TSI and got an answer a couple of hours later. A very friendly code level support engineer at apple told me, that this is probably a misconfiguration on the review teams test devices and after a couple of hours later our app got approved. So my issue had nothing to do with this library or IPv6, it was just the apple review teams fault (they are not perfect at all).
