### ISSUE TITLE
Question: Validating receipts

### ISSUE THREAD

**Issue by a-koka** [chirag04/react-native-in-app-utils#57]
Thanks for this library Chirag! Just wondering what your suggestion is in regards to fetching the `receiptData`? I'm new to mobile apps and am not sure if fetching the receipt right after a transaction is the best approach? I've noticed `receiptData` change depending on when it's fetched.

Would be nice to add something in the documentation for this to help newbies like myself.

Thank you!

**Comment by chirag04** [comment]
refer this section: https://github.com/chirag04/react-native-in-app-utils#monthly-subscriptions

**Comment by a-koka** [comment]
Thanks @chirag04. I wrote this up after reading that section and still wasn't sure when is the ideal time to fetch the receipt. Does it matter if the receipt is fetching before the transaction, right after or much after? The receipt data seems to change depending upon when it's fetched.
