### ISSUE TITLE
support react-native 0.40 iOS Headers

### ISSUE THREAD

**Issue by smkhalsa** [chirag04/react-native-in-app-utils#60]

**Comment by clementinoux** [comment]
Hello,

I've got this error on my InAppUtils.h (on line #import <RCTBridgeModule.h>) when running the simulator : 
- "<React/RCTBridgeModule.h>" file not found
 - same for "<RCTBridgeModule.h>"

I'm using "react-native": "0.39.2", can you indicate me if the version 5.0.0 is working with it ?

Thanks a lot

**Comment by smkhalsa** [comment]
v5.0 includes the changes from #61 for use with RN >=0.40.  If you are using RN<0.40, you should use v4.
