### ISSUE TITLE
Purchase Meta Data and Generic Product Identifiers

### ISSUE THREAD

**Issue by dwilt** [chirag04/react-native-in-app-utils#66]
Apple has a limit of 10,000 product identifiers per application. We are going to have more than 10,000 products in our app - thus this presents an obvious problem. Also, there is no API for creating these product identifiers and it's extremely tedious. We are looking at having generic product identifiers.

The problem with this is that when we would call `InAppUtils.restorePurchases`, we'd get no unique information back from Apple that we could use to figure out which actual product was purchased. Is there a way to pass up some specific metadata when we call `purchaseProduct` so that when we call `InAppUtils.restorePurchases` we can get that metadata back?

**Comment by dwilt** [comment]
If that can't be done, can this atleast? I see here in Apple's documentation: https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW14

That `Purchase Date`, `Original Purchase Date`, `App Item ID`, `External Version Identifier`, `Quantity`, etc.. come back with the receipt but are not available through this plugin. Can we get those added in?

**Comment by dwilt** [comment]
Having the `Purchase Date` exposed is absolutely critical.

**Comment by chirag04** [comment]
as far as i know apple does not expose any api for creating products. You need to do it from the itunesconnect.

About exposing more stuff, sure. happy to accept a PR for that.

**Comment by dwilt** [comment]
I'd love to do this but it's out of my wheelhouse. I'm a Javascript developer and know nothing about Objective-C or Swift :(. Being able to read the purchase date is something we need in our application immediately. Would you be able to put it in? I'd totally PayPal you :)

Anyone else?

**Comment by dwilt** [comment]
@chirag04 can you take a look at that PR to expose Original Purchase Date?
