### ISSUE TITLE
Can't build,React/RCTBridgeModule.h file not found 

### ISSUE THREAD

**Issue by ScorpiusZ** [chirag04/react-native-in-app-utils#67]
react-native version **0.36.1**
react-native-in-app-utils **5.1.0**
![image](https://cloud.githubusercontent.com/assets/5945675/22767338/9ef98302-eeb5-11e6-9cad-460c71ba957a.png)

should i post more info?

**Comment by ScorpiusZ** [comment]
After change  **InAppUtils.xcodeproj** build setting
add Search Path -> Header Search Path 
```
$(SRCROOT)/../react-native/React
$(SRCROOT)/../../../node_modules/react-native/React
$(SRCROOT)/../../React
```
finally  build parse

**Comment by smowden** [comment]
you should use v4 of this plugin with react versions below 0.3x

**Comment by chirag04** [comment]
@smowden is right.

**Comment by codler** [comment]
Problem still occurs.
rnpm 1.9.0
react-native 0.46.3
react-native-in-app-utils 5.5.0

**Comment by dooboolab** [comment]
Why is this closed? I am still facing the issue..

**Comment by kodayashi** [comment]
I'm also seeing this error, latest version of rnpm, react-native and react-native-in-app-utils.

**Comment by nickyhajal** [comment]
I'm seeing this as well, has anyone found a reliable fix?

**Comment by ethanyuwang** [comment]
Seeing this too
