### ISSUE TITLE
How do I check if an item is already purchased?

### ISSUE THREAD

**Issue by booboothefool** [chirag04/react-native-in-app-utils#73]
I am implementing my first in-app purchase for iOS/Android. I realized https://github.com/idehub/react-native-billing (for Android), has a way to `listOwnedProducts()`. Is there an iOS equivalent using this library, or is the iOS process just different?

Specifically, this is a non-consumable purchase "No ads".

**Comment by chirag04** [comment]
Usually you would save the purchased state on you backend for a given user.

If that's not an option, you can store what's purchases on device. There are many ways to do that outside the scope of this lib.

There also restorePurchase which you can use to find all purchased items.

On iOS there is no API to directly get purchased item other than restore purchases.

**Comment by booboothefool** [comment]
Ah, I see. I know how to do all of those then. Thanks. 

Out of curiosity, why is saving the purchased state on the backend preferred over using `restorePurchases`? I guess I need to do that on the Android too then, because it seems to save it to the Google Play account and not the user's account on my app.

In general, it is a better practice to store "already purchased" in my own user database instead of relying on App Store/Google Play?

**Comment by booboothefool** [comment]
Also, I am bit confused about the `restorePurchases`. https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Restoring.html

It says:
>Include some mechanism in your app to let the user restore their purchases, such as a Restore Purchases button. Restoring purchases prompts for the user’s App Store credentials, which interrupts the flow of your app: because of this, don’t automatically restore purchases, especially not every time your app is launched.

But after trying out `restorePurchases` from this library, it seems to do exactly what I need: gets a list of the already purchased items. I'm calling every time the user launches the app, and it doesn't seem to be prompting for credentials every time. 

Is the article just outdated? I noticed it doesn't mention anything about **non-consumables**. Are these treated differently? Because `restorePurchases` seems to work just fine.

**Comment by booboothefool** [comment]
Nevermind. It seems like it wasn't prompting me because after you do it the first time, it saves the account in iTunes/App Store settings. If this was a brand new user however, and I restore the purchases on app start, it prompts them before they even buy anything or look at the store, which seems very bad. Going to look into storing it to the user account on the backend like you said

**Comment by chirag04** [comment]
going to close as per my comment above.

**Comment by Leeds-eBooks** [comment]
Hi guys, sorry for resurrecting this issue, I just wondered if you could briefly help me with a bit of advice. I'm trying to decide where to persist the purchase receipts for non-consumable IAPs in my app, and after hours of googling I'm none the wiser. What confuses me is this: above, and in several other places on the web, the advice is to store the purchase on my own backend **for a given app user**. But unless I'm mistaken, IAPs are tied to an iTunes account, not to an app-specific user account.

For example, I might log out of my app, sign up as a different app user, then tap "restore purchases" and I would then get access to my non-consumable IAP feature without paying again.

And, conversely, if I log out of my iTunes account and sign in to my iPhone with a different iTunes account, and then log into my app with my original app account, I **won't** have access to my non-consumable IAP feature unless I pay again.

All of this to say – it makes no sense to me to store the receipt with the app-specific user account, given that the purchase is **in no way** related to that account.

Or am I (very likely!) wrong? Thanks for any help you can give!

**Comment by booboothefool** [comment]
@Leeds-eBooks I can give you some examples where I saw no other alternative than storing it on the user metadata.

1) User is logging in
2) I need to determine whether they are ad-free or not. But to do this, I shouldn't be prompting them/calling "Restore Purchases" every time. It should just be saved on their user metadata.
3) Hide/show ads accordingly
(Also like I said in a previous post, you can have a brand new user -> they log in -> you have to call Restore Purchases just to check if they bought Ad-Free, which prompts them for their iTunes info before they've even looked at your in-app store for the first time!!! Bad.)

or simply, I want to show how many "Gems" the user currently has, which would've been a consumable IAP, having to press "Restore Purchases" every time for this doesn't make sense.

I ended up going with storing it on the backend as @chirag04 suggested + offering a Restore Purchases button (which iOS review makes you do anyway).

**Comment by Leeds-eBooks** [comment]
Thanks so much for your reply.

> I need to determine whether they are ad-free or not. But to do this, I shouldn't be prompting them/calling "Restore Purchases" every time. It should just be saved on their user metadata.

If it's stored on the device, you can check without calling "Restore Purchases". If the app has been reinstalled, or we're on a new device, the user just taps "Restore Purchases" manually. I don't think this would be annoying.

> (Also like I said in a previous post, you can have a brand new user -> they log in -> you have to call Restore Purchases just to check if they bought Ad-Free, which prompts them for their iTunes info before they've even looked at your in-app store for the first time!!! Bad.)

Again, if it's stored on the device, you don't need to do this. I would never call "Restore purchases" automatically – a new app user account, on the same old iTunes account, would just tap "Restore Purchases" manually.

> Imagine if Facebook had a shitload of ads and had an IAP to remove them all forever. Wouldn't people be pissed if they upgraded from their Samsung Galaxy S7 to an iPhone 7, and had to buy that again?

This is a good point. Can I clarify something? If someone buys an IAP, then logs out of the app, then signs up with a new app account, they don't have the IAP purchase because they're a new user. But they're on the same iTunes account, so they can tap "Restore Purchases". At this point, in your app, do you store the restored purchase on this new user's account in your server?

Thanks again!

**Comment by booboothefool** [comment]
@Leeds-eBooks

Yeah, it really all depends on your use case. I don't know if you're familiar with Pokemon Go, but you could buy Pokeballs. Let's say you bought an IAP of 100 Pokeballs. No matter if you logged in from your iPhone 6, or iPhone 7, or iPad, or Android, you'd expect those Pokeballs to be there when you logged into your account, wouldn't you? In my case with the Ad-Free, my user already bought Ad-Free, so I didn't want to temporarily show them ads until they navigated to the Shop to press "Restore Purchases", which isn't even a thing on Android like it is on iOS. It seems like apps with online user profiles are a more fitting case for the backend storage. If you had an app where you didn't care if they lost their Pokeballs / progress, you could get away with something else. For example, a single-player game with unlockable maps, just using "Restore Purchases" would work fine I would imagine. As for your question, "If someone buys an IAP, then logs out of the app, then signs up with a new app account, they don't have the IAP purchase because they're a new user. But they're on the same iTunes account, so they can tap "Restore Purchases". At this point, in your app, do you store the restored purchase on this new user's account in your server?", in my case, yes. That's what I did. I don't expect them to re-buy "Ad-Free" on every account. This could be abused probably, but it's better than people getting pissed, 1 starring your app, asking for refunds, etc.

**Comment by Leeds-eBooks** [comment]
@booboothefool This is so helpful, thanks. You're totally right and as my use-case is extra premium features, you're right that a user with an account should only have to go through the purchase process once, and shouldn't be expected even to "restore purchases". And thanks for explicitly answering my last question, it really helps. Much appreciated!

**Comment by anonym24** [comment]
Android IAP Server gives all information about product (including if it's purchased or not),
So what about iOS?

It's stupid to save it locally (prefs, defaults)

Android uses Google Play Services to get purchased items even in offline mode

For safety we can validate if user is really bought (and didn't use some LuckyPatcher, Freedom to get it for free) - https://developer.android.com/google/play/billing/billing_best_practices#validating-purchase-server

This additional validation we can make when user's device internet is enabled

So how does iOS work then?

I don't want to save anything locally

**Comment by anonym24** [comment]
also implementing your own server just to check if user bought ad-free item is very excessive/expensive

our apps aren't pokemon go, your app may even not need any logging before user can use it

but yes only for pokemon go similar apps it looks good to have a server and facebook/google/other different variants to register/login in your app

**Comment by oguzhankarabulut** [comment]
@anonym24 hi, if user use our app without registiration how can we check this user already subscribe or not?

**Comment by superandrew213** [comment]
@oguzhankarabulut `InAppUtils.restorePurchases`
