### ISSUE TITLE
InAppUtils not a propery of NativeModules

### ISSUE THREAD

**Issue by GShotwell** [chirag04/react-native-in-app-utils#74]
Hi there, 

Thanks for al your work on this library. I'm having a small problem which is that when I load NativeModules it does have the InAppUtils property so this returns undefined: 

```
import { NativeModules } from 'react-native'
  const { InAppUtils } = NativeModules
...
  componentWillMount() {
    console.log(InAppUtils
}
```

I installed using both `rnpm install --save react-native-in-app-utils` and `npm install --save react-native-in-app-utils; react-native-link`. In both cases it looks like the libraries are linked properly in Xcode. 

Any ideas how I can check that the library is installed properly?

**Comment by GShotwell** [comment]
I tried uninstalling and reinstalling a few times and now it seems to work.

**Comment by christiangenco** [comment]
I installed with `yarn add react-native-in-app-utils` and it wasn't working, so I ran `react-native link` and rebuilt the app from XCode and it worked.

**Comment by hugoh1995** [comment]
Having same issue but can't make it work anyhow.

**Comment by marco-souza** [comment]
Same error, even after run `react-native link` :(
