### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by Vitaly-V** [chirag04/react-native-in-app-utils#79]
Hello, can someone post here working code example for subscription or tell me what is wrong with my code?
Thanks in advance.

I can get products from itunes connect, but I can't pay.
      
const products = [
  'com.test.test.subscription',
  'com.test.test.noncons',
];
InAppUtils.loadProducts(products, (error, productsReturned) => {
  InAppUtils.purchaseProduct(products[0], (purchaseError, response) => {
    if (response && response.productIdentifier) {
      AlertIOS.alert('Purchase Successful', `Your Transaction ID is ${response.transactionIdentifier}`);
      this.setState({
        productId
      });
    } else {
      AlertIOS.alert(purchaseError.message);
    }
  });
});

I'm testing on real device.

**Comment by juancabraal** [comment]
I'm having the same issue, I'm trying to subscribe and InAppUtils.purchaseProduct always return error, but everything is right on Apple side...

**Comment by Vitaly-V** [comment]
I didn't change anything in my code. However, now it's working for me. Perhaps it was some Apple issues.
