### ISSUE TITLE
How do you get the language specific info?

### ISSUE THREAD

**Issue by markburns** [chirag04/react-native-in-app-utils#8]
Am I right in thinking you haven't added this functionality?
The responses I get back only include product id and price. Or am I doing something wrong at my end?

**Comment by chirag04** [comment]
which language specific info exactly would you need?

**Comment by markburns** [comment]
I mean the info you register when creating the IAP on iTunesConnect. 
E.g. product name and description in the user's language.

**Comment by chirag04** [comment]
Ok. I'm not sure about that. I think apple should automatically show the popup with that info to you based on your device language?

**Comment by markburns** [comment]
OK, if it's something wrong at my end, I can close the issue. Does that mean you get to see product details when you make requests? I.e. the functionality is present?

**Comment by chirag04** [comment]
when you make the purchase request, apple will show you a popup with all the product info that you enter in itunes connect.

closing for now. Let me know something is missing here.

**Comment by markburns** [comment]
I'm not really on Objective C dev, so apologies if I'm wrong. But is this where you define it? It looks like you only return product id and price string there, right?

https://github.com/chirag04/react-native-in-app-utils/blob/master/InAppUtils/InAppUtils.m#L176

**Comment by chirag04** [comment]
yes. For now we are returning priceString and id there. We can return more stuff if available and required from there.

**Comment by markburns** [comment]
So I did a debug on `item` there and it has the following internal fields:
```
_contentVersion
_downloadable
_downloadableContentLengths
_localeIdentifier
_localizedDescription
_localizedTitle
_price
_priceLocale
_productIdentifier
```

I guess I can just add them in. Do you want a pull request?

**Comment by markburns** [comment]
Obviously the reason for needing this is that the application should display the products in the user's locale before choosing to purchase. Not just show an internal id to the user and display the real name in a popup.

**Comment by markburns** [comment]
#9 provides what I was looking for

**Comment by chirag04** [comment]
Cool. Thanks for the PR. I will merge it.
