### ISSUE TITLE
Free trial period for in-app-purchase

### ISSUE THREAD

**Issue by kawashimaken** [chirag04/react-native-in-app-utils#81]
It might not be the responsibility of this library, however I wonder if anyone have implemented the free-trial period for in-app-purchase with this lib? (For example check if the free trial period is over, etc)  Or, simply just set up the free-trail period in iTunes-connect and forget it, don't have to code anything in react native side? 

My understanding is (auto-renewal case):
(1) FIRST, user have to 'purchase' not matter the free trial period is set or not.
(2) if the app is configured to have free trial period, THEN user can use the app in that free trial period without being charged
(3) when the free trial period is over, apple's system starts to auto renew user's purchase, user still can use the app, but now user will get charged from then on.

I'l appreciate any experiences if you have some to share. Thank you! :-)

**Comment by kawashimaken** [comment]
There is nothing to set up in this Library, so I am closing this.

**Comment by chirag04** [comment]
@kawashimaken It would be nice if you can send a PR to the readme for with the setup you did. others might benefit from that.

**Comment by kawashimaken** [comment]
It's my pleasure!
https://github.com/chirag04/react-native-in-app-utils/pull/83
