### ISSUE TITLE
Question: How to leave the sandbox mode?

### ISSUE THREAD

**Issue by itinance** [chirag04/react-native-in-app-utils#87]
The issue i have recently is that the inapp-billing-process always "thinks" i am in sandbox mode. It doesn't matter if i run the app on real device in debug mode or release-mode. 
It always shows "Sandbox-Mode" when it asks for my apple-id and password.

I would expect to be in production-mode when running the app in release-mode on real-device (similar as it is to google play store). Or has it something to do with me having an Apple developer account with the same apple-id?

Even when i install the app per Testflight (ReleaseBuild) i am on the sandbox mode.

Any ideas? How will this lib differ between sandbox and production mode?

**Comment by kawashimaken** [comment]
I am having the same question.
In my production, it will pop up once or twice the dialogue asking for password for sandbox. I have no idea what cause this, any help will be appreciated!

**Comment by itinance** [comment]
@kawashimaken but this happens only on your personal device, not on the devices of other users, right? (this is what happens to me)

**Comment by chirag04** [comment]
you can use a different apple id to test the production mode. I think you can remove yourself from the sandbox users for in-app on itunes connect too.

about the dialogue popping up randomly: it can be a dev only thing where you initiated the transaction and killed/crashed the app. Apple will still try to continue the transaction.

**Comment by chirag04** [comment]
let me know if you need more info.

**Comment by itinance** [comment]
Ah, thank you @chirag04! sandbox-users, very good hint!

**Comment by kawashimaken** [comment]
My case is:
Actually my sandbox user account is A(which is only for sandbox test), and the issue happens to my apple user account B.
my B account is my daily user account and B is not a sand box user. with B account, I did purchase my product, not thing wrong with other functions so far, but it asked for my sandbox password a couple times. I will try to ask some users and confirm if they encounter the same issue.

**Comment by vitalyliber** [comment]
Hey @kawashimaken Did you have problems with the "asking sandbox password couple times" in production?

**Comment by kawashimaken** [comment]
@vitalyliber not in production. my testers didn't report anything like that, I guess maybe it is because my user account B, is also my developers account.
