### ISSUE TITLE
loadProducts works on TestFlight but not on production

### ISSUE THREAD

**Issue by mcmatan** [chirag04/react-native-in-app-utils#93]
I have used this library successfully while testing and beta testing with TestFlight.
I have uploaded my app to production and re-downloaded in from AppStore, and not products will not load any more any advice?

**Comment by amed-kino** [comment]
I assume this issue is solved.  After some hours it comes to life and works 😄 . Do you still have the issue?

**Comment by chirag04** [comment]
check if your products are approved and ready for sale. it usually take 24 hrs for them to show up
