### ISSUE TITLE
loadProducts

### ISSUE THREAD

**Issue by jingoldby** [chirag04/react-native-in-app-utils#96]
Just wondering why we need to pass a first argument to loadProducts? Am I not just fetching my products listed in itunes connect? 

Also, in the example it just passes the productId of one of the products in the store?

**Comment by chirag04** [comment]
not all your products will be on sale, you maybe not want to load all products are once. that's the underlying api from apple. first arg is an array. so you can pass as many products you want to load.

**Comment by jingoldby** [comment]
@chirag04 ah ok i see! Thanks for making this!
